version: "3.9"

services:

    backend:
        container_name: backend_dev
        build:
            context: ./backend
        command: start_prod.sh
        restart: always
        volumes:
            - static-data:/vol/django_static
        env_file: .env
        depends_on:
            - mongo-data

    mongo-data:
        container_name: mongoDb_dev
        image: mongo:3.6
        restart: always
        volumes:
            - ./dbDatas:/data/db
        env_file: .env
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=root
            - MONGO_INITDB_DATABASE=${MONGO_DB_NAME}
            - MONGO_INITDB_USER=${MONGO_DB_USERNAME}
            - MONGO_INITDB_PASS=${MONGO_DB_PASSWORD}
    
    nginx:
        container_name: nginx_prod
        build:
            context: .
            dockerfile: nginx/prod/Dockerfile
        ports: 
            - "80:80"
        depends_on:
            - backend
        volumes:
            - static-data:/vol/django_static

volumes:
    static-data:
    

