version: "3.9"

services:

    nginx:
        container_name: nginx_dev
        build:
            context: ./nginx/dev
        ports: 
            - "80:80"
        depends_on:
            - frontend
            - backend
        volumes:
            - static-data:/vol/django_static
            
    frontend:
        container_name: frontend_dev
        build:
            context: ./frontend
        restart: always
        volumes:
              - ./frontend:/app/
              - '/app/node_modules'
        ports:
            - "3000:3000"
        stdin_open: true
        environment:
            - CHOKIDAR_USEPOLLING=true
            - FAST_REFRESH=true
    
    backend:
        container_name: backend_dev
        build:
            context: ./backend
        command: start_dev.sh
        restart: always
        volumes:
            - static-data:/vol/django_static
        env_file: 
            - .env
        depends_on:
            - mongo-data

    mongo-data:
        container_name: mongoDb_dev
        image: mongo:3.6
        restart: always
        volumes:
            - ./dbDatas:/data/db
        env_file: 
            - .env
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=root
            - MONGO_INITDB_DATABASE=${MONGO_DB_NAME}
            - MONGO_INITDB_USER=${MONGO_DB_USERNAME}
            - MONGO_INITDB_PASS=${MONGO_DB_PASSWORD}

    
    mongo-express-data:
        image: mongo-express:1.0.0-alpha.4
        container_name: mongoExpress_dev
        restart: always
        env_file: 
            - .env
        environment:
            - ME_CONFIG_MONGODB_SERVER=${MONGO_DB_HOST}
            - ME_CONFIG_MONGODB_PORT=${MONGO_DB_PORT}
            - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_DB_USERNAME}
            - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_DB_PASSWORD}
            - ME_CONFIG_BASICAUTH_USERNAME=${ME_CONFIG_BASICAUTH_USERNAME}
            - ME_CONFIG_BASICAUTH_PASSWORD=${ME_CONFIG_BASICAUTH_PASSWORD}
            - ME_CONFIG_OPTIONS_EDITORTHEME=${ME_CONFIG_OPTIONS_EDITORTHEME}
        ports:
            - "8081:8081"
volumes:
    static-data: